[2022-12-07T17:39:41] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-07T17:39:47] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-07T17:39:56] WARNING [django.request.log_response:241] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-12-07T17:39:59] ERROR [django.request.log_response:241] Internal Server Error: /apps/instagram/appinfo/
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/dashboard/views.py", line 219, in appinfo
    plan = app.plan_set.all().filter(default_for_customer=True)[0]
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2022-12-07T17:40:30] INFO [root.showapps:70] yaswanth_seen the whole applist
